# Generated by Django 5.2.14 on 2026-05-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent_type', models.CharField(choices=[('individual', 'Хувь хүн'), ('organization', 'Байгууллага')], db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='agents/avatars/')),
                ('bio', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, limit_choices_to={'agent_type': 'organization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_agents', to='accounts.agent')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агентүүд',
                'ordering': ['display_name', 'company_name'],
            },
        ),
    ]
