# Generated by Django 5.2.14 on 2026-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_agency_name_remove_user_is_agent_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='agent',
            name='title',
            field=models.CharField(blank=True, help_text='Жишээ: Platinum agent, Senior broker', max_length=120),
        ),
    ]
