# Generated by Django 5.2.14 on 2026-07-20 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agent_title_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Хоосон бол хязгааргүй', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(limit_choices_to={'agent_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='accounts.agent')),
            ],
            options={
                'verbose_name': 'Урилгын код',
                'verbose_name_plural': 'Урилгын кодууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
