# Generated by Django 5.2.14 on 2026-07-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='invited_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='accounts.invitecode'),
        ),
        migrations.AddField(
            model_name='agent',
            name='membership_status',
            field=models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('approved', 'Зөвшөөрсөн'), ('denied', 'Татгалзсан')], db_index=True, default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agent_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
