# Generated by Django 5.2.14 on 2026-05-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('sell', 'Зарна'), ('rent', 'Түрээслүүлнэ'), ('buy', 'Авна')], db_index=True, max_length=20)),
                ('property_type', models.CharField(choices=[('apartment', 'Орон сууц'), ('house', 'Гэр'), ('office', 'Оффис'), ('commercial', 'Үйлчилгээний байр'), ('land', 'Газар')], db_index=True, max_length=20)),
                ('building_type', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('new', 'Шинэ'), ('excellent', 'Маш сайн'), ('good', 'Сайн'), ('fair', 'Дундаж'), ('needs_renovation', 'Засвар хэрэгтэй')], db_index=True, max_length=30)),
                ('district', models.CharField(db_index=True, max_length=50)),
                ('official_address', models.CharField(db_index=True, max_length=255)),
                ('unofficial_addresses', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_count', models.PositiveSmallIntegerField(default=1)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('total_floor', models.SmallIntegerField(blank=True, null=True)),
                ('garage', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('pending', 'Хүлээгдэж буй'), ('sold', 'Зарагдсан'), ('rented', 'Түрээслэгдсэн'), ('archived', 'Архив')], db_index=True, default='active', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/')),
                ('images', models.JSONField(blank=True, default=list)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.location')),
            ],
            options={
                'verbose_name': 'Үл хөдлөх хөрөнгө',
                'verbose_name_plural': 'Үл хөдлөх хөрөнгүүд',
                'ordering': ['-created_at'],
            },
        ),
    ]
