# Generated by Django 5.2.14 on 2026-05-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_agency_name_remove_user_is_agent_agent'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accounts.agent'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_owner_type',
            field=models.CharField(choices=[('owner', 'Зарын эзэн өөрөө'), ('agent', 'Агент'), ('company', 'Компани')], db_index=True, default='owner', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
