# Generated by Django 5.2.13 on 2026-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_agent_property_listing_owner_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='view_direction',
            field=models.CharField(blank=True, choices=[('', 'Тодорхойгүй'), ('north', 'Хойд'), ('south', 'Өмнөд'), ('east', 'Зүүн'), ('west', 'Баруун'), ('northeast', 'Зүүн хойд'), ('northwest', 'Баруун хойд'), ('southeast', 'Зүүн өмнөд'), ('southwest', 'Баруун өмнөд'), ('panoramic', 'Панорам'), ('city', 'Хотын үзэсгэлэн'), ('mountain', 'Уулын үзэсгэлэн'), ('courtyard', 'Дотоод талбай')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='window_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
