# Generated by Django 5.2.13 on 2026-06-29 07:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_user_agency_name_remove_user_is_agent_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('individual', 'Хувь хүн агент'), ('organization', 'Байгууллага')], db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('billing_period', models.CharField(choices=[('monthly', 'Сар бүр'), ('yearly', 'Жил бүр')], default='monthly', max_length=20)),
                ('max_listings', models.PositiveIntegerField(default=5)),
                ('max_vip_listings', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Багц',
                'verbose_name_plural': 'Багцууд',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('cancelled', 'Цуцлагдсан'), ('expired', 'Дууссан'), ('trial', 'Туршилт')], db_index=True, default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.agent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалгууд',
                'ordering': ['-started_at'],
            },
        ),
    ]
