# Generated by Django 5.2.14 on 2026-05-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.CharField(choices=[('baganuur', 'Багануур'), ('bagakhangai', 'Багахангай'), ('bayangol', 'Баянгол'), ('bayanzurkh', 'Баянзүрх'), ('khan_uul', 'Хан-Уул'), ('nalaikh', 'Налайх'), ('songinokhairkhan', 'Сонгинохайрхан'), ('sukhbaatar', 'Сүхбаатар'), ('chingeltei', 'Чингэлтэй'), ('hud', 'Хан-Уул дүүрэг (ХУД)')], db_index=True, max_length=50)),
                ('official_address', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршилууд',
                'ordering': ['district', 'official_address'],
            },
        ),
        migrations.CreateModel(
            name='LocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='locations.location')),
            ],
            options={
                'verbose_name': 'Байршлын нэр',
                'verbose_name_plural': 'Байршлын нэрүүд',
                'ordering': ['name'],
                'unique_together': {('location', 'name')},
            },
        ),
    ]
